# Generated by Django 2.2.10 on 2020-06-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='ticket.Organization'),
            preserve_default=False,
        ),
    ]
