# Generated by Django 2.2.10 on 2020-06-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_auto_20200607_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
